### ISSUE TITLE
Question about Android studio use

### ISSUE THREAD

**Issue by Phone-Guru** [TeamSubstratum/SubstratumThemeTemplate#15]
I managed to open the project in android studio.  It tells me that the project doesn't use gradle to build.  I tried to disable Instant run but I don't have to since it only works with gradle.  Any idea what went wrong

**Comment by KreAch3R** [comment]
Chances are, it's not project related. Follow every guide you can find on the internet about fixing that, or delete everything and try to redownload the repo and open in in Studio.

Is this the first time you try to build anything with AS?
