### ISSUE TITLE
A few questions about the NavBar

### ISSUE THREAD

**Issue by s5bug** [TeamSubstratum/SubstratumThemeTemplate#18]
Can you explain how to do these things?

- [ ] Disable Pixel home button circle (but keep the dot animation)
- [ ] Change Pixel dot images that come out (if possible)
- [x] Disable scaling of the home button in landscape
- [ ] Change the keyboard button that comes up in a keyboard
- [ ] Change the three dots that come up in a menu

What I have now is [here](https://github.com/firestar115/smwtheme).

**Comment by s5bug** [comment]
To disable bad scaling in landscape of the home button, create an `ic_sysbar_home_land`.

**Comment by s5bug** [comment]
In Gboard, it looks like there's a `ic_notification_small_icon`. Gonna look into that

EDIT: Changing the icon in an overlay has no visible effect?

**Comment by xdevs23** [comment]
@firestar115 https://open.spotify.com/track/110chxuuMT6rXsEco9QYSb?context=spotify%3Auser%3Aspotify%3Aplaylist%3A37i9dQZEVXbl0ZgurZWM2x

**Comment by nathanchance** [comment]
If this is still something you're struggling with, please ask it in [the Google+ community](https://plus.google.com/communities/102261717366580091389) or [our XDA thread](https://forum.xda-developers.com/apps/substratum/qa-questions-theming-t3585703). Issues should only be for template related issues.
