### ISSUE TITLE
No explanation how to add colors for type1 extensions

### ISSUE THREAD

**Issue by andrzejressel** [TeamSubstratum/SubstratumThemeTemplate#19]
Recently a feature was added to substratum that allows themers to add colors for their type1 extensions ([shown here](https://www1-lw.xda-cdn.com/files/2017/03/Screenshot_20170304-093201.jpg)). However there are no instruction on how to add them to theme.

**Comment by KreAch3R** [comment]
Hey @jereksel , that's correct. It should be the first color inside the .xml.

@nathanchance, can you update the instructions? :D

**Comment by nicholaschum** [comment]
I will update it. Thanks
