### ISSUE TITLE
I can't hide app from launcher

### ISSUE THREAD

**Issue by isagardb** [TeamSubstratum/SubstratumThemeTemplate#22]
If I remove " category android:name="android.intent.category.LAUNCHER" /> " from manifest ...I can run (compile) the app...

**Comment by msfjarvis** [comment]
What are you even trying to do?

> I can't hide app from launcher

 It doesn't even show up.

> If I remove " category android:name="android.intent.category.LAUNCHER" /> " from manifest ...I can run (compile) the app...

There is no such intent-filter action in the template's [AndroidManifest](https://github.com/substratum/template/blob/master/app/src/main/AndroidManifest.xml)
