### ISSUE TITLE
Error while applying the theme 

### ISSUE THREAD

**Issue by EnCoderX** [TeamSubstratum/SubstratumThemeTemplate#23]
» [com.android.deskclock]: ERROR: resource directory '/data/user/0/projekt.substratum/cache/SubstratumBuilder/res/' does not exist
» [com.android.deskclock]: Installation of "com.android.deskclock" has failed.

When no changes are made to the theme then everything installs perfectly. 
But when I try my own overlays. These issues come up. 
New to development, please help me dev!

**Comment by jerbeck24** [comment]
Does this work with my theme? I'm confused... Mine applies fine on my phone.

**Comment by R3DMaNX** [comment]
That's because your overlay is not in the package name structure... com.android.deskclock/res/

**Comment by EnCoderX** [comment]
Thank You very much bud !

**Comment by Shikhar0018** [comment]
What does this mean then how I need to resolve

**Comment by akhilnarang** [comment]
@Shikhar0018
