### ISSUE TITLE
Navbar help

### ISSUE THREAD

**Issue by one-om-jha** [TeamSubstratum/SubstratumThemeTemplate#27]
My navbar icons are functioning but there are a few major bugs. First, they each appear down and to the right compared to where they should be, and it appears the size affects them. For example, setting "android:width","android:height","android:viewportWidth", and "android:viewportHeight" to 30 shows nothing, but 70 shows them down and to the right but also huge, and 144 puts them in the correct spot but makes them way too big. The home key is also always slightly smaller, and when all three are set to 144, the home key is _tiny_. Thanks!

**Comment by nathanchance** [comment]
If this is still something you're struggling with, please ask it in [the Google+ community](https://plus.google.com/communities/102261717366580091389) or [our XDA thread](https://forum.xda-developers.com/apps/substratum/qa-questions-theming-t3585703). Issues should only be for template related issues.
