### ISSUE TITLE
SubstratumAntiPiracyLog fails to generate

### ISSUE THREAD

**Issue by dully79** [TeamSubstratum/SubstratumThemeTemplate#35]
Template kt-n 10.0.1

**Comment by ivaniskandar** [comment]
Please retry using this https://github.com/iskandar1023/template/tree/kt-n and report back

**Comment by dully79** [comment]
Will do, thank you.

**Comment by dully79** [comment]
SubstratumAntiPiracyLog gets generated in release only.

Substratum 391 hangs when accessing theme.
Edit: it hangs whilst trying to contact store to verify license.

Everything seems as it should be.
Thank you Ivan.
