### ISSUE TITLE
Maven's address now invalid

### ISSUE THREAD

**Issue by ghost** [TeamSubstratum/SubstratumThemeTemplate#46]
Hello :)
I have not download the dependes yet, and the maven's adress has changed.
So I fall into trouble when I am tring to download some dependes by automatic.
It now should be like this:https://dl.google.com/dl/android/maven2/
Old one didn't work now :(

**Comment by nicholaschum** [comment]
I just forked the repository and it worked fine. Have you updated to Android Studio Canary 6?

**Comment by ghost** [comment]
It works after I just updated my Android Studio to 2.3.3 release version.Thanks for your reply :)
