### ISSUE TITLE
Compatibility with Android Studio 2.3.3

### ISSUE THREAD

**Issue by GroovinChip** [TeamSubstratum/SubstratumThemeTemplate#53]
I've set up this project in Android Studio but it will not build because it requires Android Studio 3.0 beta. How can I get the project to work with the stable Android Studio?

**Comment by msfjarvis** [comment]
@GroovinChip You don't. Nothing wrong with canary.

**Comment by venedele** [comment]
@GroovinChip I managed to get it to finish the Gradle sync  by cleaning project and then filling in the right version for Gradle and Android plugin in ProjectSettings -> Project.
Still haven't tried compiling it but I think that if the Gradle sync is successful there will be no problem in compilation.

**Comment by boswelja** [comment]
Why not use canary? I haven't found any bugs in it
