### ISSUE TITLE
Question on Java branch status

### ISSUE THREAD

**Issue by Bokoblin** [TeamSubstratum/SubstratumThemeTemplate#55]
Hello,

The Java branch hasn't been updated since June, do you still plan to update it ?
There are two reasons for which I'd like the Java branch to be updated :
- For the moment, AS3.0 which support Kotlin, is still in Beta so I can't compile it with AS2.3.3
- We should have the choice between Java and Kotlin, both are official Android languages, and more people use Java

Thanks

**Comment by msfjarvis** [comment]
All our themers use AS3.x without complaints so that's not really a valid point. Secondly, more people using java would have mattered if you were supposed to actually change much of the source code, which you do not. There are no plans for updating the java branch.

**Comment by Bokoblin** [comment]
Okay, thanks for the status update. I'll keep working on the java branch for the moment and will move to Kotlin branch when AS3.0 stable will be released.
