### ISSUE TITLE
Allow themers to include more information about theme compatiblity

### ISSUE THREAD

**Issue by andrzejressel** [TeamSubstratum/SubstratumThemeTemplate#56]
Regarding [this](https://plus.google.com/+HarshShandilya99/posts/1pEiWc4Q52C)

Include meta-data information about AOSP, CustomROM, OxygenOS, Nougat, Oreo compatibility and enforce it in Substratum.

**Comment by YechiamW3** [comment]
@jereksel Yechiam Weiss:
What will that help?
Users that don't read won't read it no matter where it's displayed. Example: Swift themes.

**Comment by andrzejressel** [comment]
After selecting theme could dialog displayed saying that: "This theme is not compatible with your current configuration: AOSP Oreo (depending on user's device).". On dialog there would be button "Enter anyway", so user is notified that theme is compatible and there could be issues during/after compiling.

**Comment by YechiamW3** [comment]
@jereksel Themers can easily use the projekt.substratum.theme permission to lock the themes to nougat custom roms.
