### ISSUE TITLE
No type3 common description

### ISSUE THREAD

**Issue by andrzejressel** [TeamSubstratum/SubstratumThemeTemplate#57]
Recently support for "type3 common" was merged to dev (https://github.com/substratum/substratum/commit/1d7b810f4fc083a0001bbf6ef141881584380509), but there is no documentation about it in Google Docs document.

**Comment by nathanchance** [comment]
That commit is in our dev branch for a reason. Documentation will be synced up when we merge into the release branch, as that's when it becomes relevant for themers.
