### ISSUE TITLE
Please update README

### ISSUE THREAD

**Issue by ElTifo** [TeamSubstratum/SubstratumThemeTemplate#67]
Please update the README. I had a lot of issues after building the apk and push it to Play Store.

My suggestion:

"Compile your theme as a SIGNED release APK from Android Studio (Build -> Generate Signed APK). Then launch the signed apk on your device and your log will spit out an error log under the name "SubstratumThemeReport", and you want to copy and paste that into APK_SIGNATURE_PRODUCTION on line 10.

**NOTE**: You only need to do this if you **DON'T PLAN** to use Google Play App Signing on your Google Play Console. If you plan to use it, **leave it blank** or the users, who'll download it from Google Play Store, will not be able to use your theme."

Thanks in advance.

**Comment by msfjarvis** [comment]
You could have easily sent a pull request with the changes you've described rather than start an issue and saved both of our times. I'll see what I can do about it.

**Comment by ElTifo** [comment]
Sorry for not using the proper way.
