### ISSUE TITLE
Not showing in substratum app

### ISSUE THREAD

**Issue by emreaydogdu** [TeamSubstratum/SubstratumThemeTemplate#69]
If I debug the template app on my phone it would be not listed in the substratum app.
How can i fix that??

**Comment by MihailMihov** [comment]
**1. GitHub Issues is not the way to ask for help.**
2. You are probably on a Samsung device and you didn't change the ThemeSupportsSamsung value to true in res/theme_configuretions.xml. Or if the app doesn't install you most likely have to change your minSdkVersion to your device's Sdk version or lower.

**Comment by yash-garg** [comment]
@MihailMihov Lel

**Comment by MihailMihov** [comment]
@Yash-Garg I really don't understand whats so funny? If you think what I said is wrong you could've given a more correct answer, instead of replying with _lel_

**Comment by msfjarvis** [comment]
This has run it's course.
