### ISSUE TITLE
Apps crashing

### ISSUE THREAD

**Issue by hybrid101** [TeamSubstratum/SubstratumThemeTemplate#70]
Hello, i don't know where else to ask and i searched google for over 1 hour, came out empty..
Everytime i declare a custom made color in a colors.xml in a random app then i use it on a color already declared, after i apply the theme, the app always crashes.
Now, i'm a noob when it comes to Substratum, played alot with CMTE back in the days, but this has got my head spinning.
I tried several apps (dialer,settings,file manager), always the same result.

My colors.xml looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<color name="dialer_theme_color">@color/mycolors</color>
	<color name="mycolors">#ffff0000</color>
</resources>
```
It only crashes if i set `@color/mycolors`. If i just change the original color, it's working fine.
Why can't i put my own colors in apps?
What am i doing wrong? (This worked fine in CMTE)

Btw, i'm on a RR rom.

**Comment by Adarsh-MR** [comment]
its because you cant add new resource "mycolor", you have to use resources which is already available in apk, you can just use hex instead referencing it to another resource.

**Comment by hybrid101** [comment]
But some things in styles.xml, for example can't use hex code and it's not only on colors. I can't even add a new drawable xml file (a solid color). Basically, i can't add anything custom made in an app, though this worked fine in CMTE. There has to be something i'm not seeing or doing.

Let's say i wanna make my background half red transparent. If i add a half_red_transparent.xml in drawables and set it there, then if i reference it somewhere in my styles.xml, the app crashes.

**Comment by msfjarvis** [comment]
CMTE allowed adding new resources, OMS does not. Any theming related queries you have do not belong here, you can ask them in the [G+ community](https://plus.google.com/communities/102261717366580091389) or in the [Telegram chat](https://t.me/ThemingHelp). I'm closing and locking this issue.
