### ISSUE TITLE
Create theme info

### ISSUE THREAD

**Issue by fraom** [TeamSubstratum/SubstratumThemeTemplate#80]
Hi thanks for this template, i ve some questions because i don t understand how to start.
There is a full tutorial for how to made a theme? 
For example i do not understand how to change quick settings icons or icons in settings page.
Thanks

**Comment by ai94iq** [comment]
Hi there, template already has examples of overlays for system apps under /assets/overlays, you could build the template as is, then build the overlays with subs to see the effects, then do the changes

or you could always check guide over xda, like this one
https://forum.xda-developers.com/galaxy-s4/themes-apps/guide-how-to-theme-tw-systemui-t3065965

**Comment by gcantoni** [comment]
You can give a look to my Pixel theme which is open source

https://github.com/gcantoni/pixeltheme
