### ISSUE TITLE
FC on Samsung's Adapt Sound 

### ISSUE THREAD

**Issue by asar19** [TeamSubstratum/SubstratumThemeTemplate#81]
Samsung Adapt Sound crashes and force closes when trying to edit Sound Profiles. My Samsung Galaxy S8+ is themed with the Swift Installer Engine.

**Comment by msfjarvis** [comment]
This is not related to the template, if you have issues theming then join the Theming Help chat from our [Telegram link portal](https://t.me/substratum/)

**Comment by gcantoni** [comment]
Gib log to devs . No one will help you here. Pretty surprised that GitHub is now theme issues report lol
