### ISSUE TITLE
import groovy.io.FileType

### ISSUE THREAD

**Issue by Ardjlon** [TeamSubstratum/SubstratumThemeTemplate#87]
Can not resolve symbol FileType

**Comment by msfjarvis** [comment]
`./gradlew clean assembleDebug` compiles [perfectly fine](https://del.dog/raw/petavasaso) though? Please add actual meaningful information here.

**Comment by Ardjlon** [comment]
Can't upload the local changes,  and i need upload all clone.

**Comment by msfjarvis** [comment]
I still don't understand what the issue at hand is
